In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [9]:
df = pd.read_csv("Heart_dataset.csv" )
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [10]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [11]:
df = df.drop("Unnamed: 0",axis=1)

In [12]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [13]:
df.shape

(303, 14)

In [14]:
df.columns

Index(['Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR',
       'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [15]:
df.dtypes

Age            int64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD           object
dtype: object

In [ ]:
ca_m = df["Ca"].mode    
ca_m

<bound method Series.mode of 0      0.0
1      3.0
2      2.0
3      0.0
4      0.0
      ...
298    0.0
299    2.0
300    1.0
301    1.0
302    NaN
Name: Ca, Length: 303, dtype: float64>

In [ ]:
df1  = df["Ca"].fillna(value=0.0)
df1.isnull()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Name: Ca, Length: 303, dtype: bool

In [18]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [19]:
le = LabelEncoder()

In [20]:
thal_values = le.fit_transform(df["Thal"])
thal_values

array([0, 1, 2, 1, 1, 1, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 0, 2, 1, 2, 2, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2,
       1, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 3,
       1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 0, 2, 2, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 0, 2,
       2, 0, 1, 1, 2, 2, 1, 2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 0, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 0, 3, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 0,
       0, 2, 2, 1, 2, 1, 0, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1])

In [21]:
df["Thal"]=thal_values
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         0
AHD          0
dtype: int64

In [ ]:
#adding cloumn df1 in df["ca"]
df["Ca"]=df1

In [24]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [25]:
num_AHD = le.fit_transform(df["AHD"])

In [26]:
df["AHD"] = num_AHD

In [27]:
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,0,0
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,1,1
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,2,1
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,1,0
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,2,1
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,2,1
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,2,1
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,1,1
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,0.0,1,0

In [28]:
num_chest_pain = le.fit_transform(df["ChestPain"])
num_chest_pain

array([3, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 2, 3, 3,
       2, 1, 0, 1, 1, 3, 0, 0, 3, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 3, 2, 1,
       0, 1, 1, 0, 1, 1, 2, 0, 0, 2, 0, 0, 1, 0, 1, 3, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 1, 1, 2, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 3, 0, 1, 1, 2, 0, 1, 0, 0,
       0, 0, 3, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 3, 2, 0, 0, 2, 0, 1, 1,
       2, 0, 1, 2, 0, 2, 0, 1, 2, 3, 2, 1, 1, 1, 0, 1, 2, 1, 3, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 3, 3, 0, 2, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 3, 0,
       2, 3, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 3, 1, 0, 0, 3, 2, 0, 0, 0,
       1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 2, 2, 2, 2,
       0, 3, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 2, 2, 1, 2, 3, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 3, 3, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 0, 0, 3, 0, 0, 2, 1])

In [29]:
df["ChestPain"]=num_chest_pain

In [30]:
df

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1
302,38,1,1,138,175,0,0,173,0,0.0,1,0.0,1,0

In [31]:
X = df.drop("AHD", axis=1)
y = df["AHD"]

In [32]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [34]:
y_pred = clf.predict(X_test)

In [35]:

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.819672131147541

In [36]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[23  6]
 [ 5 27]]